import sys
from pyqtgraph import PlotWidget
from PyQt5 import QtCore, QtGui, QtWidgets
import ApplicationManager

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1299, 960)
        MainWindow.setStyleSheet("background-color: #1e1e2f;\n""color:white;\n""")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(461, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.Title = QtWidgets.QTextBrowser(self.centralwidget)
        self.Title.setMinimumSize(QtCore.QSize(200, 51))
        self.Title.setMaximumSize(QtCore.QSize(341, 51))
        self.Title.setStyleSheet("border:none;")
        self.Title.setObjectName("Title")
        self.gridLayout_3.addWidget(self.Title, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(461, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("color: black;")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.Load = QtWidgets.QWidget()
        self.Load.setStyleSheet("")
        self.Load.setObjectName("Load")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.Load)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frame_5 = QtWidgets.QFrame(self.Load)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.Loaded_Signal_PlotWidget = PlotWidget(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Loaded_Signal_PlotWidget.sizePolicy().hasHeightForWidth())
        self.Loaded_Signal_PlotWidget.setSizePolicy(sizePolicy)
        self.Loaded_Signal_PlotWidget.setObjectName("Loaded_Signal_PlotWidget")
        self.gridLayout_10.addWidget(self.Loaded_Signal_PlotWidget, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: white ;\n""")
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_6, 0, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_15 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: white ;\n""")
        self.label_15.setObjectName("label_15")
        self.gridLayout_11.addWidget(self.label_15, 0, 0, 1, 1)
        self.Load_Reconstructed_PlotWidget = PlotWidget(self.frame_11)
        self.Load_Reconstructed_PlotWidget.setObjectName("Load_Reconstructed_PlotWidget")
        self.gridLayout_11.addWidget(self.Load_Reconstructed_PlotWidget, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_11, 0, 1, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("color: white;\n""")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Load_Button = QtWidgets.QPushButton(self.groupBox_2, clicked = lambda: MAESTRO.load_signal())
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Load_Button.setFont(font)
        self.Load_Button.setStyleSheet("background-color:#3366ff;\n""color: white;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/load1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Load_Button.setIcon(icon)
        self.Load_Button.setObjectName("Load_Button")
        self.horizontalLayout_7.addWidget(self.Load_Button)
        self.Load_Signals_ComboBox = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Load_Signals_ComboBox.sizePolicy().hasHeightForWidth())
        self.Load_Signals_ComboBox.setSizePolicy(sizePolicy)
        self.Load_Signals_ComboBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Load_Signals_ComboBox.setFont(font)
        self.Load_Signals_ComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Load_Signals_ComboBox.setStyleSheet("background-color:#3366ff;\n""color: white")
        self.Load_Signals_ComboBox.setObjectName("Load_Signals_ComboBox")
        self.Load_Signals_ComboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.Load_Signals_ComboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: white ;\n""")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.Load_Hertz_CheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Load_Hertz_CheckBox.setFont(font)
        self.Load_Hertz_CheckBox.setStyleSheet("color: white;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Assets/radio-waves (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Load_Hertz_CheckBox.setIcon(icon1)
        self.Load_Hertz_CheckBox.setIconSize(QtCore.QSize(44, 44))
        self.Load_Hertz_CheckBox.setObjectName("Load_Hertz_CheckBox")
        self.horizontalLayout_6.addWidget(self.Load_Hertz_CheckBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.Load_x2Fmax_CheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.Load_x2Fmax_CheckBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Load_x2Fmax_CheckBox.setFont(font)
        self.Load_x2Fmax_CheckBox.setStyleSheet("color: white;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Assets/performance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Load_x2Fmax_CheckBox.setIcon(icon2)
        self.Load_x2Fmax_CheckBox.setIconSize(QtCore.QSize(50, 50))
        self.Load_x2Fmax_CheckBox.setChecked(True)
        self.Load_x2Fmax_CheckBox.setObjectName("Load_x2Fmax_CheckBox")
        self.horizontalLayout_6.addWidget(self.Load_x2Fmax_CheckBox)
        self.Load_x2Fmax_CheckBox.stateChanged.connect(lambda: MAESTRO.plot_samples())
        self.Load_Hertz_CheckBox.stateChanged.connect(lambda: MAESTRO.plot_samples())
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Load_Sampling_Frequency_Slider = QtWidgets.QSlider(self.groupBox_2)
        self.Load_Sampling_Frequency_Slider.setMinimum(1)
        self.Load_Sampling_Frequency_Slider.setMaximum(100)
        self.Load_Sampling_Frequency_Slider.setProperty("value", 0)
        self.Load_Sampling_Frequency_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Load_Sampling_Frequency_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Load_Sampling_Frequency_Slider.setTickInterval(5)
        self.Load_Sampling_Frequency_Slider.setObjectName("Load_Sampling_Frequency_Slider")
        self.Load_Sampling_Frequency_Slider.valueChanged.connect(lambda: MAESTRO.plot_samples())
        self.horizontalLayout_4.addWidget(self.Load_Sampling_Frequency_Slider)
        self.Load_Sampling_Frequency_LCD = QtWidgets.QLCDNumber(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Load_Sampling_Frequency_LCD.setFont(font)
        self.Load_Sampling_Frequency_LCD.setStyleSheet("border:none;")
        self.Load_Sampling_Frequency_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Load_Sampling_Frequency_LCD.setLineWidth(1)
        self.Load_Sampling_Frequency_LCD.setProperty("intValue", 0)
        self.Load_Sampling_Frequency_LCD.setObjectName("Load_Sampling_Frequency_LCD")
        
        self.horizontalLayout_4.addWidget(self.Load_Sampling_Frequency_LCD)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: white ;\n""")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Load_Signal_to_Noise_Slider = QtWidgets.QSlider(self.groupBox_2)
        self.Load_Signal_to_Noise_Slider.setMinimum(1)
        self.Load_Signal_to_Noise_Slider.setMaximum(50)
        self.Load_Signal_to_Noise_Slider.setProperty("value", 100)
        self.Load_Signal_to_Noise_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Load_Signal_to_Noise_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Load_Signal_to_Noise_Slider.setTickInterval(5)
        self.Load_Signal_to_Noise_Slider.setObjectName("Load_Signal_to_Noise_Slider")
        self.Load_Signal_to_Noise_Slider.valueChanged.connect(lambda: MAESTRO.add_noise(self.Load_Signal_to_Noise_Slider.value()))
        self.horizontalLayout_5.addWidget(self.Load_Signal_to_Noise_Slider)
        self.Load_Signal_to_Noise_LCD = QtWidgets.QLCDNumber(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Load_Signal_to_Noise_LCD.setFont(font)
        self.Load_Signal_to_Noise_LCD.setStyleSheet("border:none;")
        self.Load_Signal_to_Noise_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Load_Signal_to_Noise_LCD.setProperty("intValue", 0)
        self.Load_Signal_to_Noise_LCD.setObjectName("Load_Signal_to_Noise_LCD")
        self.horizontalLayout_5.addWidget(self.Load_Signal_to_Noise_LCD)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.gridLayout_13.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_12, 1, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_20 = QtWidgets.QLabel(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: white ;\n""")
        self.label_20.setObjectName("label_20")
        self.gridLayout_14.addWidget(self.label_20, 0, 0, 1, 1)
        self.Load_Difference_PlotWidget = PlotWidget(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Load_Difference_PlotWidget.sizePolicy().hasHeightForWidth())
        self.Load_Difference_PlotWidget.setSizePolicy(sizePolicy)
        self.Load_Difference_PlotWidget.setObjectName("Load_Difference_PlotWidget")
        self.gridLayout_14.addWidget(self.Load_Difference_PlotWidget, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_13, 1, 1, 1, 1)
        self.gridLayout_15.addWidget(self.frame_5, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Task 1/Signal-Viewer/Assets/load1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Load, icon3, "")
        self.Compose = QtWidgets.QWidget()
        self.Compose.setObjectName("Compose")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.Compose)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_3 = QtWidgets.QFrame(self.Compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: white ;\n""")
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.Composed_Signal_PlotWidget = PlotWidget(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Composed_Signal_PlotWidget.sizePolicy().hasHeightForWidth())
        self.Composed_Signal_PlotWidget.setSizePolicy(sizePolicy)
        self.Composed_Signal_PlotWidget.setObjectName("Composed_Signal_PlotWidget")
        self.gridLayout_6.addWidget(self.Composed_Signal_PlotWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: white ;\n""")
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        self.Compose_Reconstructed_PlotWidget = PlotWidget(self.frame_8)
        self.Compose_Reconstructed_PlotWidget.setObjectName("Compose_Reconstructed_PlotWidget")
        self.gridLayout_7.addWidget(self.Compose_Reconstructed_PlotWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_8, 0, 1, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color: white;\n""")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Compose_Button = QtWidgets.QPushButton(self.groupBox, clicked = lambda : MAESTRO.add_component())
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Compose_Button.setFont(font)
        self.Compose_Button.setStyleSheet("background-color:#3366ff;\n""color: white;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Assets/writing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Compose_Button.setIcon(icon4)
        self.Compose_Button.setObjectName("Compose_Button")
        self.horizontalLayout.addWidget(self.Compose_Button)
        self.Compose_Components_ComboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Compose_Components_ComboBox.sizePolicy().hasHeightForWidth())
        self.Compose_Components_ComboBox.setSizePolicy(sizePolicy)
        self.Compose_Components_ComboBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Compose_Components_ComboBox.setFont(font)
        self.Compose_Components_ComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Compose_Components_ComboBox.setStyleSheet("background-color:#3366ff;\n""color: white")
        self.Compose_Components_ComboBox.setObjectName("Compose_Components_ComboBox")
        self.Compose_Components_ComboBox.addItem("")
        self.Compose_Components_ComboBox.currentIndexChanged.connect(lambda : MAESTRO.update_sliders())
        self.horizontalLayout.addWidget(self.Compose_Components_ComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Compose_Remove_Component_Button = QtWidgets.QPushButton(self.groupBox ,clicked = lambda : MAESTRO.remove_component())
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Compose_Remove_Component_Button.setFont(font)
        self.Compose_Remove_Component_Button.setStyleSheet("background-color:#3366ff;\n""color: white;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Assets/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Compose_Remove_Component_Button.setIcon(icon5)
        self.Compose_Remove_Component_Button.setObjectName("Compose_Remove_Component_Button")
        self.horizontalLayout_2.addWidget(self.Compose_Remove_Component_Button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: white ;\n""")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.Compose_Hertz_CheckBox = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Compose_Hertz_CheckBox.setFont(font)
        self.Compose_Hertz_CheckBox.setStyleSheet("color: white;")
        self.Compose_Hertz_CheckBox.setIcon(icon1)
        self.Compose_Hertz_CheckBox.setIconSize(QtCore.QSize(40, 40))
        self.Compose_Hertz_CheckBox.setObjectName("Compose_Hertz_CheckBox")
        self.horizontalLayout_3.addWidget(self.Compose_Hertz_CheckBox)
        self.Compose_x2Fmax_CheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.Compose_x2Fmax_CheckBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Compose_x2Fmax_CheckBox.setFont(font)
        self.Compose_x2Fmax_CheckBox.setStyleSheet("color: white;")
        self.Compose_x2Fmax_CheckBox.setIcon(icon2)
        self.Compose_x2Fmax_CheckBox.setIconSize(QtCore.QSize(50, 50))
        self.Compose_x2Fmax_CheckBox.setChecked(True)
        self.Compose_x2Fmax_CheckBox.setObjectName("Compose_x2Fmax_CheckBox")
        self.horizontalLayout_3.addWidget(self.Compose_x2Fmax_CheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Compose_Sampling_Frequency_Slid = QtWidgets.QSlider(self.groupBox)
        self.Compose_Sampling_Frequency_Slid.setMinimum(1)
        self.Compose_Sampling_Frequency_Slid.setMaximum(100)
        self.Compose_Sampling_Frequency_Slid.setProperty("value", 1)
        self.Compose_Sampling_Frequency_Slid.setOrientation(QtCore.Qt.Horizontal)
        self.Compose_Sampling_Frequency_Slid.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Compose_Sampling_Frequency_Slid.setTickInterval(5)
        self.Compose_Sampling_Frequency_Slid.setObjectName("Compose_Sampling_Frequency_Slid")
        self.horizontalLayout_12.addWidget(self.Compose_Sampling_Frequency_Slid)
        self.Compose_Sampling_Frequency_LCD = QtWidgets.QLCDNumber(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Compose_Sampling_Frequency_LCD.setFont(font)
        self.Compose_Sampling_Frequency_LCD.setStyleSheet("border:none;")
        self.Compose_Sampling_Frequency_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Compose_Sampling_Frequency_LCD.setProperty("intValue", 0)
        self.Compose_Sampling_Frequency_LCD.setObjectName("Compose_Sampling_Frequency_LCD")
        self.horizontalLayout_12.addWidget(self.Compose_Sampling_Frequency_LCD)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: white ;\n""")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.Compose_Signal_to_Noise_Slider = QtWidgets.QSlider(self.groupBox)
        self.Compose_Signal_to_Noise_Slider.setMinimum(1)
        self.Compose_Signal_to_Noise_Slider.setMaximum(50)
        self.Compose_Signal_to_Noise_Slider.setProperty("value", 0)
        self.Compose_Signal_to_Noise_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Compose_Signal_to_Noise_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Compose_Signal_to_Noise_Slider.setTickInterval(5)
        self.Compose_Signal_to_Noise_Slider.setObjectName("Compose_Signal_to_Noise_Slider")
        self.horizontalLayout_13.addWidget(self.Compose_Signal_to_Noise_Slider)
        self.Load_Signal_to_Noise_LCD_2 = QtWidgets.QLCDNumber(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Load_Signal_to_Noise_LCD_2.setFont(font)
        self.Load_Signal_to_Noise_LCD_2.setStyleSheet("border:none;")
        self.Load_Signal_to_Noise_LCD_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Load_Signal_to_Noise_LCD_2.setProperty("intValue", 0)
        self.Load_Signal_to_Noise_LCD_2.setObjectName("Load_Signal_to_Noise_LCD_2")
        self.horizontalLayout_13.addWidget(self.Load_Signal_to_Noise_LCD_2)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: white ;\n""")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.Compose_Signal_Frequency_Slider = QtWidgets.QSlider(self.groupBox)
        self.Compose_Signal_Frequency_Slider.setMinimum(0)
        self.Compose_Signal_Frequency_Slider.setMaximum(10)
        self.Compose_Signal_Frequency_Slider.setProperty("value", 0)
        self.Compose_Signal_Frequency_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Compose_Signal_Frequency_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Compose_Signal_Frequency_Slider.setTickInterval(1)
        self.Compose_Signal_Frequency_Slider.setObjectName("Compose_Signal_Frequency_Slider")
        self.Compose_Signal_Frequency_Slider.valueChanged.connect(lambda : MAESTRO.update_frequency())
        self.horizontalLayout_15.addWidget(self.Compose_Signal_Frequency_Slider)
        self.Compose_Signal_Frequency_LCD = QtWidgets.QLCDNumber(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Compose_Signal_Frequency_LCD.setFont(font)
        self.Compose_Signal_Frequency_LCD.setStyleSheet("border:none;")
        self.Compose_Signal_Frequency_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Compose_Signal_Frequency_LCD.setProperty("intValue", 0)
        self.Compose_Signal_Frequency_LCD.setObjectName("Compose_Signal_Frequency_LCD")
        self.horizontalLayout_15.addWidget(self.Compose_Signal_Frequency_LCD)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: white ;\n""")
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.Compose_Signal_Magnitude_Slider = QtWidgets.QSlider(self.groupBox)
        self.Compose_Signal_Magnitude_Slider.setMinimum(0)
        self.Compose_Signal_Magnitude_Slider.setMaximum(10)
        self.Compose_Signal_Magnitude_Slider.setProperty("value", 0)
        self.Compose_Signal_Magnitude_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Compose_Signal_Magnitude_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Compose_Signal_Magnitude_Slider.setTickInterval(1)
        self.Compose_Signal_Magnitude_Slider.setObjectName("Compose_Signal_Magnitude_Slider")
        self.Compose_Signal_Magnitude_Slider.valueChanged.connect(lambda: MAESTRO.update_magnitude())
        self.horizontalLayout_14.addWidget(self.Compose_Signal_Magnitude_Slider)
        self.Compose_Signal_Magnitude_LCD = QtWidgets.QLCDNumber(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Compose_Signal_Magnitude_LCD.setFont(font)
        self.Compose_Signal_Magnitude_LCD.setStyleSheet("border:none;")
        self.Compose_Signal_Magnitude_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Compose_Signal_Magnitude_LCD.setProperty("intValue", 0)
        self.Compose_Signal_Magnitude_LCD.setObjectName("Compose_Signal_Magnitude_LCD")
        self.horizontalLayout_14.addWidget(self.Compose_Signal_Magnitude_LCD)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem14, 3, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem15, 0, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem16, 2, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_9, 1, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: white ;\n""")
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.Compose_Difference_PlotWidget = PlotWidget(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Compose_Difference_PlotWidget.sizePolicy().hasHeightForWidth())
        self.Compose_Difference_PlotWidget.setSizePolicy(sizePolicy)
        self.Compose_Difference_PlotWidget.setObjectName("Compose_Difference_PlotWidget")
        self.gridLayout_5.addWidget(self.Compose_Difference_PlotWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_10, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_3, 0, 0, 1, 1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("writing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Compose, icon6, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1299, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Compose_Signal_Frequency_Slider.valueChanged['int'].connect(self.Compose_Signal_Frequency_LCD.display) # type: ignore
        self.Compose_Signal_Magnitude_Slider.valueChanged['int'].connect(self.Compose_Signal_Magnitude_LCD.display) # type: ignore
        self.Compose_Signal_to_Noise_Slider.valueChanged['int'].connect(self.Load_Signal_to_Noise_LCD_2.display) # type: ignore
        self.Load_Signal_to_Noise_Slider.valueChanged['int'].connect(self.Load_Signal_to_Noise_LCD.display) # type: ignore
        self.Compose_Sampling_Frequency_Slid.valueChanged['int'].connect(self.Compose_Sampling_Frequency_LCD.display) # type: ignore
        self.Load_Sampling_Frequency_Slider.valueChanged['int'].connect(self.Load_Sampling_Frequency_LCD.display) # type: ignore
        self.Load_Hertz_CheckBox.clicked.connect(self.Load_x2Fmax_CheckBox.toggle) # type: ignore
        self.Load_x2Fmax_CheckBox.clicked.connect(self.Load_Hertz_CheckBox.toggle) # type: ignore
        self.Compose_Hertz_CheckBox.clicked.connect(self.Compose_x2Fmax_CheckBox.toggle) # type: ignore
        self.Compose_x2Fmax_CheckBox.clicked.connect(self.Compose_Hertz_CheckBox.toggle) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sampling Studio"))
        self.Title.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Signals Sampling Studio</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "Loaded Signal"))
        self.label_15.setText(_translate("MainWindow", "Reconstructed Signal"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Loaded Signal Control"))
        self.Load_Button.setText(_translate("MainWindow", "    Load Signal"))
        self.Load_Signals_ComboBox.setItemText(0, _translate("MainWindow", "Signal 1"))
        self.label_16.setText(_translate("MainWindow", "Sampling Frequency"))
        self.Load_Hertz_CheckBox.setText(_translate("MainWindow", "Hertz"))
        self.Load_x2Fmax_CheckBox.setText(_translate("MainWindow", "F max"))
        self.label_17.setText(_translate("MainWindow", "Signal To Noise Level"))
        self.label_20.setText(_translate("MainWindow", "Difference Between Reconstructed and Original"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Load), _translate("MainWindow", "Load"))
        self.label_7.setText(_translate("MainWindow", "Composed Signal"))
        self.label_8.setText(_translate("MainWindow", "Reconstructed Signal"))
        self.groupBox.setTitle(_translate("MainWindow", "Composed Signal Control"))
        self.Compose_Button.setText(_translate("MainWindow", "  Compose Signal"))
        self.Compose_Components_ComboBox.setItemText(0, _translate("MainWindow", "Component 1"))
        self.Compose_Remove_Component_Button.setText(_translate("MainWindow", "   Remove Component"))
        self.label_10.setText(_translate("MainWindow", "Sampling Frequency"))
        self.Compose_Hertz_CheckBox.setText(_translate("MainWindow", "Hertz"))
        self.Compose_x2Fmax_CheckBox.setText(_translate("MainWindow", "F max"))
        self.label_11.setText(_translate("MainWindow", "Signal To Noise Level"))
        self.label_12.setText(_translate("MainWindow", "Composed Signal Frequency"))
        self.label_13.setText(_translate("MainWindow", "Composed Signal Magnitude"))
        self.label_9.setText(_translate("MainWindow", "Difference Between Reconstructed and Composed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Compose), _translate("MainWindow", "Compose"))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MAESTRO = ApplicationManager.ApplicationManager(ui, ui.Loaded_Signal_PlotWidget, ui.Load_Reconstructed_PlotWidget, ui.Load_Difference_PlotWidget, ui.Composed_Signal_PlotWidget, ui.Compose_Reconstructed_PlotWidget, ui.Compose_Difference_PlotWidget)
    MainWindow.show()
    sys.exit(app.exec_())
